# workflow name
name: Generate release-artifacts

# on events
on:
  workflow_dispatch:
  push:
  release:
    types:
        - created

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            name: 'rss-to-podcast'
            compress: 'false'
            dest: 'dist'
      - name: Upload build artifacts
        uses: actions/upload-artifact@main
        with:
           path: ./dist/*
      - name: Release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
      - name: Upload as release
        id: releas_upload
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: ./dist/*

      #- name: Upload build artifacts
        #uses: skx/github-action-publish-binaries@master
        #env:
            #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #with:
            #args: ./dist/*
